### ISSUE TITLE
ModuleNotFoundError: No module named 'xtuner.parallel'

### ISSUE THREAD

**Issue by starlitsky2010** [open-compass/VLMEvalKit#139]
I met this problem when test by cmd:
torchrun --nproc-per-node=8 --nnodes=1 --node_rank=0 --master_addr 10.255.244.33 --master_port 8109 run.py --data LLaVABench --model llava-internlm2-20b --verbose

Traceback (most recent call last):
  File "/code/src/VLMEvalKit/run.py", line 153, in <module>
    main()
  File "/code/src/VLMEvalKit/run.py", line 83, in main
    model = infer_data_job(
  File "/code/src/VLMEvalKit/vlmeval/inference.py", line 210, in infer_data_job
    model = infer_data(
  File "/code/src/VLMEvalKit/vlmeval/inference.py", line 142, in infer_data
    response = model.generate(prompt=struct['text'], image_path=struct['image'], dataset=dataset_name)
  File "/code/src/VLMEvalKit/vlmeval/vlm/llava_xtuner.py", line 177, in generate
    from xtuner.model.utils import prepare_inputs_labels_for_multimodal
  File "/usr/local/lib/python3.10/dist-packages/xtuner/model/__init__.py", line 3, in <module>
    from .sft import SupervisedFinetune
  File "/usr/local/lib/python3.10/dist-packages/xtuner/model/sft.py", line 16, in <module>
    from xtuner.parallel.sequence import (get_sequence_parallel_world_size,
ModuleNotFoundError: No module named 'xtuner.parallel'
[2024-04-03 03:58:31,981] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2207729) of binary: /bin/python

**Comment by kennymckormick** [comment]
Did you install the latest version of xtuner? We recommend you to install xtuner from the source code (latest main branch at https://github.com/InternLM/xtuner). 
BTW, do you have any idea on the potential reason of this error @LZHgrla

**Comment by LZHgrla** [comment]
@starlitsky2010 Hi!

There is some package bugs on xtuner==0.1.16.

Install xtuner>=0.1.17 can solve this issue.

```
pip install 'xtuner>=0.1.17'
```

**Comment by starlitsky2010** [comment]
> Did you install the latest version of xtuner? We recommend you to install xtuner from the source code (latest main branch at https://github.com/InternLM/xtuner). BTW, do you have any idea on the potential reason of this error @LZHgrla

I used xtuner==0.1.15 and that fixes it. Thanks
