### ISSUE TITLE
evaluate TextVQA_VAL  error

### ISSUE THREAD

**Issue by LRHstudy** [open-compass/VLMEvalKit#237]
# command
python run.py --data TextVQA_VAL --model cogvlm2-llama3-chat-19B --verbose

# env
python 3.8
torch 2.1.0+cu118
VLMEvalKit: the lastest main branch

# error message
Did not detect the .env file at /code/lmdeploy_test/VLMEvalKit/.env, failed to load. 
Did not detect the .env file at /code/lmdeploy_test/VLMEvalKit/.env, failed to load. 
/code/lmdeploy_test/VLMEvalKit/vlmeval/utils/dataset.py:60: UserWarning: The dataset tsv is not downloaded
  warnings.warn('The dataset tsv is not downloaded')
TextVQA_VAL.tsv: 1.22GB [03:34, 5.70MB/s]                                                                                                   
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/code/lmdeploy_test/VLMEvalKit/vlmeval/tools.py", line 266, in decode_img_omni
    decode_base64_to_image_file(im, p)
  File "/code/lmdeploy_test/VLMEvalKit/vlmeval/smp/vlm.py", line 71, in decode_base64_to_image_file
    image = decode_base64_to_image(base64_string, target_size=target_size)
  File "/code/lmdeploy_test/VLMEvalKit/vlmeval/smp/vlm.py", line 61, in decode_base64_to_image
    image_data = base64.b64decode(base64_string)
  File "/usr/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 160, in <module>
    main()
  File "run.py", line 79, in main
    model = infer_data_job(
  File "/code/lmdeploy_test/VLMEvalKit/vlmeval/inference.py", line 164, in infer_data_job
    model = infer_data(
  File "/code/lmdeploy_test/VLMEvalKit/vlmeval/inference.py", line 72, in infer_data
    dataset = TSVDataset(dataset_name)
  File "/code/lmdeploy_test/VLMEvalKit/vlmeval/utils/dataset.py", line 84, in __init__
    self.data_path = prep_tsv(dataset)
  File "/code/lmdeploy_test/VLMEvalKit/vlmeval/utils/dataset.py", line 71, in prep_tsv
    LOCALIZE(data_path, local_path)
  File "/code/lmdeploy_test/VLMEvalKit/vlmeval/tools.py", line 291, in LOCALIZE
    ret = pool.map(decode_img_omni, tups)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
binascii.Error: Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4

**Comment by kennymckormick** [comment]
Hi, @LRHstudy , 
The problem has been fixed now.
