### ISSUE TITLE
评测时PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by 40459447** [open-compass/VLMEvalKit#454]
Traceback (most recent call last):
  File "D:\opencompass1\VLMEvalKit\run.py", line 223, in <module>
    main()
  File "D:\opencompass1\VLMEvalKit\run.py", line 137, in main
    model = infer_data_job(
  File "D:\opencompass1\VLMEvalKit\vlmeval\inference.py", line 162, in infer_data_job
    model = infer_data(
  File "D:\opencompass1\VLMEvalKit\vlmeval\inference.py", line 102, in infer_data
    supp = infer_data_api(
  File "D:\opencompass1\VLMEvalKit\vlmeval\inference.py", line 60, in infer_data_api
    track_progress_rich(gen_func, structs, nproc=api_nproc, chunksize=api_nproc, save=out_file, keys=indices)
  File "D:\opencompass1\VLMEvalKit\vlmeval\utils\mp_util.py", line 188, in track_progress_rich
    raise e
  File "D:\opencompass1\VLMEvalKit\vlmeval\utils\mp_util.py", line 174, in track_progress_rich
    ans = load(save)
  File "D:\opencompass1\VLMEvalKit\vlmeval\smp\file.py", line 177, in load
    return handlers[suffix](f)
  File "D:\opencompass1\VLMEvalKit\vlmeval\smp\file.py", line 150, in load_pkl
    return pickle.load(open(pth, 'rb'))
PermissionError: [Errno 13] Permission denied

**Comment by kennymckormick** [comment]
Hi, @40459447 , 
The toolkit is developed for Linux and we are not sure if it runs properly on Windows platform
